# Generated by Django 6.1.1 on 2026-09-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('established_year', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'developers',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('action', 'Экшен'), ('rpg', 'RPG'), ('strategy', 'Стратегия'), ('sports', 'Спорт'), ('simulation', 'Симулятор')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('developer', models.ForeignKey(db_column='developer_id', on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api_v1.developer')),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api_v1.game')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
